apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: webapp
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "<insert your mail>"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class:  kong